// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: proto/match/match.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单方向
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_match_match_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_proto_match_match_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{0}
}

// 订单类型
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_match_match_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_proto_match_match_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{1}
}

// 订单状态
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIAL     OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED      OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PARTIAL",
		3: "ORDER_STATUS_FILLED",
		4: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PARTIAL":     2,
		"ORDER_STATUS_FILLED":      3,
		"ORDER_STATUS_CANCELLED":   4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_match_match_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_match_match_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{2}
}

// 提交订单请求
type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Side          OrderSide              `protobuf:"varint,3,opt,name=side,proto3,enum=match.OrderSide" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,4,opt,name=type,proto3,enum=match.OrderType" json:"type,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,7,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_proto_match_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitOrderRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *SubmitOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubmitOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SubmitOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

// 提交订单响应
type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=match.OrderStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_proto_match_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *SubmitOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 取消订单请求
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_match_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 取消订单响应
type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_match_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 订单簿查询
type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_proto_match_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderBookRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GetOrderBookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type OrderBookLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderCount    int32                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookLevel) Reset() {
	*x = OrderBookLevel{}
	mi := &file_proto_match_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookLevel) ProtoMessage() {}

func (x *OrderBookLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookLevel.ProtoReflect.Descriptor instead.
func (*OrderBookLevel) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{5}
}

func (x *OrderBookLevel) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderBookLevel) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderBookLevel) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type GetOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Bids          []*OrderBookLevel      `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*OrderBookLevel      `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookResponse) Reset() {
	*x = GetOrderBookResponse{}
	mi := &file_proto_match_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookResponse) ProtoMessage() {}

func (x *GetOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderBookResponse) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GetOrderBookResponse) GetBids() []*OrderBookLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderBookResponse) GetAsks() []*OrderBookLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetOrderBookResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 最近成交查询
type GetRecentTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentTradesRequest) Reset() {
	*x = GetRecentTradesRequest{}
	mi := &file_proto_match_match_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentTradesRequest) ProtoMessage() {}

func (x *GetRecentTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentTradesRequest.ProtoReflect.Descriptor instead.
func (*GetRecentTradesRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecentTradesRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GetRecentTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TakerSide     OrderSide              `protobuf:"varint,5,opt,name=taker_side,json=takerSide,proto3,enum=match.OrderSide" json:"taker_side,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_proto_match_match_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{8}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Trade) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetTakerSide() OrderSide {
	if x != nil {
		return x.TakerSide
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Trade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetRecentTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentTradesResponse) Reset() {
	*x = GetRecentTradesResponse{}
	mi := &file_proto_match_match_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentTradesResponse) ProtoMessage() {}

func (x *GetRecentTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentTradesResponse.ProtoReflect.Descriptor instead.
func (*GetRecentTradesResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecentTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// 行情订阅
type SubscribeTickerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterIds  []string               `protobuf:"bytes,1,rep,name=character_ids,json=characterIds,proto3" json:"character_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTickerRequest) Reset() {
	*x = SubscribeTickerRequest{}
	mi := &file_proto_match_match_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTickerRequest) ProtoMessage() {}

func (x *SubscribeTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTickerRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTickerRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeTickerRequest) GetCharacterIds() []string {
	if x != nil {
		return x.CharacterIds
	}
	return nil
}

type TickerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	LastPrice     int64                  `protobuf:"varint,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	OpenPrice     int64                  `protobuf:"varint,3,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	HighPrice     int64                  `protobuf:"varint,4,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice      int64                  `protobuf:"varint,5,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	Volume        int64                  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	ChangeRate    float64                `protobuf:"fixed64,7,opt,name=change_rate,json=changeRate,proto3" json:"change_rate,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerEvent) Reset() {
	*x = TickerEvent{}
	mi := &file_proto_match_match_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerEvent) ProtoMessage() {}

func (x *TickerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerEvent.ProtoReflect.Descriptor instead.
func (*TickerEvent) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{11}
}

func (x *TickerEvent) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *TickerEvent) GetLastPrice() int64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *TickerEvent) GetOpenPrice() int64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *TickerEvent) GetHighPrice() int64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *TickerEvent) GetLowPrice() int64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *TickerEvent) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TickerEvent) GetChangeRate() float64 {
	if x != nil {
		return x.ChangeRate
	}
	return 0
}

func (x *TickerEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 成交订阅
type SubscribeTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterIds  []string               `protobuf:"bytes,1,rep,name=character_ids,json=characterIds,proto3" json:"character_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTradesRequest) Reset() {
	*x = SubscribeTradesRequest{}
	mi := &file_proto_match_match_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTradesRequest) ProtoMessage() {}

func (x *SubscribeTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTradesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTradesRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeTradesRequest) GetCharacterIds() []string {
	if x != nil {
		return x.CharacterIds
	}
	return nil
}

type TradeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TakerSide     OrderSide              `protobuf:"varint,4,opt,name=taker_side,json=takerSide,proto3,enum=match.OrderSide" json:"taker_side,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeEvent) Reset() {
	*x = TradeEvent{}
	mi := &file_proto_match_match_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeEvent) ProtoMessage() {}

func (x *TradeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeEvent.ProtoReflect.Descriptor instead.
func (*TradeEvent) Descriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{13}
}

func (x *TradeEvent) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *TradeEvent) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeEvent) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeEvent) GetTakerSide() OrderSide {
	if x != nil {
		return x.TakerSide
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *TradeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_match_match_proto protoreflect.FileDescriptor

const file_proto_match_match_proto_rawDesc = "" +
	"\n" +
	"\x17proto/match/match.proto\x12\x05match\"\xf6\x01\n" +
	"\x12SubmitOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12$\n" +
	"\x04side\x18\x03 \x01(\x0e2\x10.match.OrderSideR\x04side\x12$\n" +
	"\x04type\x18\x04 \x01(\x0e2\x10.match.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12&\n" +
	"\x0fclient_order_id\x18\a \x01(\tR\rclientOrderId\"v\n" +
	"\x13SubmitOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.match.OrderStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\x12CancelOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"I\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x13GetOrderBookRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"c\n" +
	"\x0eOrderBookLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x05R\n" +
	"orderCount\"\xad\x01\n" +
	"\x14GetOrderBookResponse\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12)\n" +
	"\x04bids\x18\x02 \x03(\v2\x15.match.OrderBookLevelR\x04bids\x12)\n" +
	"\x04asks\x18\x03 \x03(\v2\x15.match.OrderBookLevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"Q\n" +
	"\x16GetRecentTradesRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xbb\x01\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12/\n" +
	"\n" +
	"taker_side\x18\x05 \x01(\x0e2\x10.match.OrderSideR\ttakerSide\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"?\n" +
	"\x17GetRecentTradesResponse\x12$\n" +
	"\x06trades\x18\x01 \x03(\v2\f.match.TradeR\x06trades\"=\n" +
	"\x16SubscribeTickerRequest\x12#\n" +
	"\rcharacter_ids\x18\x01 \x03(\tR\fcharacterIds\"\x81\x02\n" +
	"\vTickerEvent\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x03R\tlastPrice\x12\x1d\n" +
	"\n" +
	"open_price\x18\x03 \x01(\x03R\topenPrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x04 \x01(\x03R\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\x05 \x01(\x03R\blowPrice\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x03R\x06volume\x12\x1f\n" +
	"\vchange_rate\x18\a \x01(\x01R\n" +
	"changeRate\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"=\n" +
	"\x16SubscribeTradesRequest\x12#\n" +
	"\rcharacter_ids\x18\x01 \x03(\tR\fcharacterIds\"\xb0\x01\n" +
	"\n" +
	"TradeEvent\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12/\n" +
	"\n" +
	"taker_side\x18\x04 \x01(\x0e2\x10.match.OrderSideR\ttakerSide\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02*\x94\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14ORDER_STATUS_PARTIAL\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x042\xc4\x03\n" +
	"\fMatchService\x12D\n" +
	"\vSubmitOrder\x12\x19.match.SubmitOrderRequest\x1a\x1a.match.SubmitOrderResponse\x12D\n" +
	"\vCancelOrder\x12\x19.match.CancelOrderRequest\x1a\x1a.match.CancelOrderResponse\x12G\n" +
	"\fGetOrderBook\x12\x1a.match.GetOrderBookRequest\x1a\x1b.match.GetOrderBookResponse\x12P\n" +
	"\x0fGetRecentTrades\x12\x1d.match.GetRecentTradesRequest\x1a\x1e.match.GetRecentTradesResponse\x12F\n" +
	"\x0fSubscribeTicker\x12\x1d.match.SubscribeTickerRequest\x1a\x12.match.TickerEvent0\x01\x12E\n" +
	"\x0fSubscribeTrades\x12\x1d.match.SubscribeTradesRequest\x1a\x11.match.TradeEvent0\x01B\x12Z\x10o7m2/proto/matchb\x06proto3"

var (
	file_proto_match_match_proto_rawDescOnce sync.Once
	file_proto_match_match_proto_rawDescData []byte
)

func file_proto_match_match_proto_rawDescGZIP() []byte {
	file_proto_match_match_proto_rawDescOnce.Do(func() {
		file_proto_match_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_match_match_proto_rawDesc), len(file_proto_match_match_proto_rawDesc)))
	})
	return file_proto_match_match_proto_rawDescData
}

var file_proto_match_match_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_match_match_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_match_match_proto_goTypes = []any{
	(OrderSide)(0),                  // 0: match.OrderSide
	(OrderType)(0),                  // 1: match.OrderType
	(OrderStatus)(0),                // 2: match.OrderStatus
	(*SubmitOrderRequest)(nil),      // 3: match.SubmitOrderRequest
	(*SubmitOrderResponse)(nil),     // 4: match.SubmitOrderResponse
	(*CancelOrderRequest)(nil),      // 5: match.CancelOrderRequest
	(*CancelOrderResponse)(nil),     // 6: match.CancelOrderResponse
	(*GetOrderBookRequest)(nil),     // 7: match.GetOrderBookRequest
	(*OrderBookLevel)(nil),          // 8: match.OrderBookLevel
	(*GetOrderBookResponse)(nil),    // 9: match.GetOrderBookResponse
	(*GetRecentTradesRequest)(nil),  // 10: match.GetRecentTradesRequest
	(*Trade)(nil),                   // 11: match.Trade
	(*GetRecentTradesResponse)(nil), // 12: match.GetRecentTradesResponse
	(*SubscribeTickerRequest)(nil),  // 13: match.SubscribeTickerRequest
	(*TickerEvent)(nil),             // 14: match.TickerEvent
	(*SubscribeTradesRequest)(nil),  // 15: match.SubscribeTradesRequest
	(*TradeEvent)(nil),              // 16: match.TradeEvent
}
var file_proto_match_match_proto_depIdxs = []int32{
	0,  // 0: match.SubmitOrderRequest.side:type_name -> match.OrderSide
	1,  // 1: match.SubmitOrderRequest.type:type_name -> match.OrderType
	2,  // 2: match.SubmitOrderResponse.status:type_name -> match.OrderStatus
	8,  // 3: match.GetOrderBookResponse.bids:type_name -> match.OrderBookLevel
	8,  // 4: match.GetOrderBookResponse.asks:type_name -> match.OrderBookLevel
	0,  // 5: match.Trade.taker_side:type_name -> match.OrderSide
	11, // 6: match.GetRecentTradesResponse.trades:type_name -> match.Trade
	0,  // 7: match.TradeEvent.taker_side:type_name -> match.OrderSide
	3,  // 8: match.MatchService.SubmitOrder:input_type -> match.SubmitOrderRequest
	5,  // 9: match.MatchService.CancelOrder:input_type -> match.CancelOrderRequest
	7,  // 10: match.MatchService.GetOrderBook:input_type -> match.GetOrderBookRequest
	10, // 11: match.MatchService.GetRecentTrades:input_type -> match.GetRecentTradesRequest
	13, // 12: match.MatchService.SubscribeTicker:input_type -> match.SubscribeTickerRequest
	15, // 13: match.MatchService.SubscribeTrades:input_type -> match.SubscribeTradesRequest
	4,  // 14: match.MatchService.SubmitOrder:output_type -> match.SubmitOrderResponse
	6,  // 15: match.MatchService.CancelOrder:output_type -> match.CancelOrderResponse
	9,  // 16: match.MatchService.GetOrderBook:output_type -> match.GetOrderBookResponse
	12, // 17: match.MatchService.GetRecentTrades:output_type -> match.GetRecentTradesResponse
	14, // 18: match.MatchService.SubscribeTicker:output_type -> match.TickerEvent
	16, // 19: match.MatchService.SubscribeTrades:output_type -> match.TradeEvent
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_match_match_proto_init() }
func file_proto_match_match_proto_init() {
	if File_proto_match_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_match_match_proto_rawDesc), len(file_proto_match_match_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_match_match_proto_goTypes,
		DependencyIndexes: file_proto_match_match_proto_depIdxs,
		EnumInfos:         file_proto_match_match_proto_enumTypes,
		MessageInfos:      file_proto_match_match_proto_msgTypes,
	}.Build()
	File_proto_match_match_proto = out.File
	file_proto_match_match_proto_goTypes = nil
	file_proto_match_match_proto_depIdxs = nil
}
